apiVersion: v1
kind: PersistentVolume
metadata:
  name: bt-volume
  labels:
    name: bt-volume
spec:
  capacity:
    storage: 50Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: bt-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: bt-postgre-pvc
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 50Gi
    volumeName: bt-volume